area/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls', namespace="polls")),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.main, name='home'),
    path('popular', views.popular, name='popular'),
    path('about', views.about, name='about'),
    path('news/<slug:title>/', views.item, name='new'),    
]

polls/models.py
from django.db import models
from datetime import date
import datetime

  

class New(models.Model):
    title = models.CharField(max_length=201)    
    pub_date = models.CharField(default=str(datetime.datetime.today), max_length=300)    
    content = models.CharField(max_length=200)    
    img_url = models.CharField(max_length=200)    
    url_name = models.CharField(max_length=200, default="")  
    views = models.IntegerField(default=0)  

class User(models.Model):
    login = models.CharField(max_length=100, default="") 
    password = models.CharField(max_length=100, default="") 
    FIO = models.CharField(max_length=100, default="")

polls/views.py
from .models import New
from django.shortcuts import render
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger        
from datetime import datetime, timezone
COUNT_BLOCKS_ON_PAGE = 10

def item(request, title): 

    current_new = New.objects.filter(url_name=title).first()
    current_new.views += 1
    print(current_new.pub_date)
    current_new.save()

    return render(request, 'page.html', {
        "current_new": current_new,
    })  

def about(request):     
    return render(request, 'about.html', {        
    })  
    
def utc_to_local(utc_dt):
    return utc_dt.replace(tzinfo=timezone.utc).astimezone(tz=None)

def main(request):      
    pub_date = request.GET.get('pub_date')              
    title = request.GET.get('title')
        
    snews = New.objects.all()    

    
        

    if pub_date:
        snews = snews.filter(pub_date__icontains=pub_date)
    else:
        pub_date = ""
    if title:    
        snews = snews.filter(title__icontains=title)
    else:
        title = ""
    paginator = Paginator(snews, COUNT_BLOCKS_ON_PAGE)     
    page = request.GET.get('page')        
    try:
        page = int(page)
    except:
        page = 1
    a = ""
    snews = ""
    pages=[]
    if page:
        try:
            snews = paginator.page(page)
        except EmptyPage:
            snews = paginator.page(paginator.num_pages)
            page = paginator.num_pages

        for i in range(page-2, page+3):
            try:
                a = paginator.page(i)
                pages.append(i)
            except:
                continue        
        if pages[-1] != paginator.num_pages:
            pages.append(paginator.num_pages)

        if pages[0] != 1:
            pages.insert(0, 1)
    else:
        pages = [1,2,3,4,5,paginator.num_pages]
        snews = paginator.page(1)
    
    popular = New.objects.order_by("-views")[:5]

    return render(request, 'news.html', {
        'snews': snews,
        'pub_date': pub_date,  
        "title": title,     
        "pages": pages,
        "popular": popular,
    })  

def popular(request):      
    pub_date = request.GET.get('pub_date')              
    title = request.GET.get('title')
        
    snews = New.objects.order_by("-views")  
    if pub_date:
        snews = snews.filter(pub_date__icontains=pub_date)
    else:
        pub_date = ""
    if title:    
        snews = snews.filter(title__icontains=title)
    else:
        title = ""
    paginator = Paginator(snews, COUNT_BLOCKS_ON_PAGE)     
    page = request.GET.get('page')        
    try:
        page = int(page)
    except:
        page = 1
    a = ""
    snews = ""
    pages=[]
    if page:
        try:
            snews = paginator.page(page)
        except EmptyPage:
            snews = paginator.page(paginator.num_pages)
            page = paginator.num_pages

        for i in range(page-2, page+3):
            try:
                a = paginator.page(i)
                pages.append(i)
            except:
                continue        
        if pages[-1] != paginator.num_pages:
            pages.append(paginator.num_pages)

        if pages[0] != 1:
            pages.insert(0, 1)
    else:
        pages = [1,2,3,4,5,paginator.num_pages]
        snews = paginator.page(1)
    
    popular = New.objects.order_by("-views")[:5]

    return render(request, 'popular.html', {
        'snews': snews,
        'pub_date': pub_date,  
        "title": title,     
        "pages": pages,
        "popular": popular,
    })  
      

polls/templates/about.html
{% extends "base.html" %}
{% load static %}

{% block styles %}    
        <link rel="stylesheet" href="{% static 'polls/styles/main.css'%}">
    <link rel="stylesheet" href="{% static 'polls/styles/bootstrap-datepicker.css'%}">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
{% endblock %}

{% block input_block %}
    <input type="text" name="title" class="form-control search" placeholder="Введите название" value="{{title}}">
{% endblock %}

{% block header_buttons %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'polls:home'%}">Главная</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'polls:popular'%}">Популярное</a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'polls:about'%}">О нас</a>
    </li>    
{% endblock %}


{% block container %}
    <div class="container">
        <div class="row  mt-4">
            <div class="col col-md-7">
                <h1 class="text-center">Sober</h1>
                <h4 class="mt-4 ">Молодые перспективные ребята примутся за любую вашу работу вне зависимости от сложности и масштабности разработки</h4>
                <p class="mt-5">По всем вопросам обращаться по телефону: <a href="">8-800-555-35-35</a></p>
                
            </div>
            <div class="col col-md-5">
                    <ul class="list-group">
                        <li class="list-group-item">Разработка сайта на bootstrap</li>
                        <li class="list-group-item">Макет сайта</li>
                        <li class="list-group-item">Дизайн</li>
                        <li class="list-group-item">Адаптивная и отзывчивая верстка</li>
                        <li class="list-group-item">Доработка функционала сайта</li>
                        <li class="list-group-item">Разработка на PHP, Python, Node.js</li>
                    </ul>  
            </div>
        </div>
    </div>
{% endblock %}

polls/templates/base.html
{% load static %}
<!DOCTYPE html>

{% block head %}    
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1" />        
        <title>sNews</title>
        {% block styles %}
            
        {% endblock %}                
    </head>
{% endblock %}

{% block body %}
    <body>
        {% block header %}            
            <header>
                <nav class="navbar navbar-expand-lg">
                    <div class="container">
                        <img class="navbar-brand" src="{% static 'polls/images/logo.jpg' %}">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-4"
                            aria-controls="navbarSupportedContent-4" aria-expanded="false" aria-label="Toggle navigation">
                            <img class="navbar-toggler-icon" src="{% static 'polls/images/menu.png' %}">
                        </button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent-4">
                            <ul class="navbar-nav mr-auto">
                                {% block header_buttons %}
                                {% endblock %}
                            </ul>
                            <form class="form-inline my-2 my-lg-0 ml-auto " type="GET" action="{% url 'polls:home'%}" >
                                {% block input_block %}
                                {% endblock %}
                                <div class="input-group-append">
                                    <button class="btn btn-search" type="submit">Найти</button>
                                </div>
                            </form>
                        </div>

                        
                    </div>
                </nav>
            </header>
            
        {% endblock %}

        {% block content %}
            {% block container %}
                
            {% endblock %}

            {% block footer %}
                <!-- Footer -->
                <footer class="page-footer font-small blue">
                    <div class="footer-copyright text-center py-2">© 2019-2020 Sober:
                    <a href="https://snews.pythonanywhere.com/">snews.pythonanywhere.com</a>
                    </div>
                </footer>

                {% block scripts %}
                {% endblock %}
            {% endblock %}
        {% endblock %}  
        <style type="text/css">#hellopreloader>p{display:none;}#hellopreloader_preload{display: block;position: fixed;z-index: 99999;top: 0;left: 0;width: 100%;height: 100%;min-width: 100px;background: white url({% static 'polls/images/350.gif'%}) center center no-repeat;background-size:88px;}</style>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>      
        <div id="hellopreloader"><div id="hellopreloader_preload"></div><p><a href="http://hello-site.ru">Hello-Site.ru. Бесплатный конструктор сайтов.</a></p></div>
    <script type="text/javascript">var hellopreloader = document.getElementById("hellopreloader_preload");function fadeOutnojquery(el){el.style.opacity = 1;var interhellopreloader = setInterval(function(){el.style.opacity = el.style.opacity - 0.05;if (el.style.opacity <=0.05){ clearInterval(interhellopreloader);hellopreloader.style.display = "none";}},16);}window.onload = function(){setTimeout(function(){fadeOutnojquery(hellopreloader);},1000);};</script>
    </body>
{% endblock %}

polls/templates/news.html
{% extends "base.html" %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'polls/styles/main.css'%}">
    <link rel="stylesheet" href="{% static 'polls/styles/bootstrap-datepicker.css'%}">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
{% endblock %}

{% block header_buttons %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'polls:home'%}">Главная</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'polls:popular'%}">Популярное</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'polls:about'%}">О нас</a>
    </li>    
{% endblock %}

{% block input_block %}
    <input type="text" name="title" class="form-control search" placeholder="Введите название" value="{{title}}">
{% endblock %}

{% block container %}
    <div class="container">
        <div class="row">

            <!-- Video -->            
            <div class="col left">
                <h1 class="pg-title-tran">
                    Трансляция
                </h1>
                <div id="ytplayer" class="d-flex mr-3" ></div>    
                <img src="{% static 'polls/images/line.png'%}" alt="" class="line">
                <h1 class="pg-title-top">
                    Популярное
                </h1>
                <ul class="top">

                    <!-- FOREACH -->
                        {% for item in popular %}
                            <a href="{% url 'polls:new' item.url_name %}">
                                <li class="media">
                                    <div class="media-body">
                                        <h5 class="mt-0 mb-1 font-weight-bold">
                                            {{item.title}}
                                        </h5>
                                        <span class="date">
                                            {{item.pub_date}}
                                        </span>
                                    </div>
                                </li>
                            </a>
                        {% endfor %}
                    <!-- /FOREACH -->
    
                </ul>
            </div>

            <!-- News -->
            <div class="col col-lg-8">
                <h1 class="pg-title">
                    Новости
                </h1>


                <!-- DATEPICKER -->
                <form action="" type="GET" class="input-group mb-3">
                    <input type="text" name="pub_date" autocomplete="off" value="{{pub_date}}" id="datepicker" class="form-control datepicker" placeholder="Выберите дату">
                    <div class="input-group-append">
                        <button class="btn" type="submit">Просмотреть новости</button>
                    </div>
                </form>
                <!-- <input type="hidden" id="my_hidden_input"> -->

                <ul class="list-unstyled">
                    {% for item in snews%}
                        <a href="{% url 'polls:new' item.url_name%}">
                            <li class="media my-4">
                                <img class="d-flex mr-3" src="{{item.img_url}}" alt="Generic placeholder image">                            
                                <div class="media-body">
                                        <h5 class="mt-0 mb-1 font-weight-bold">{{item.title}}</h5>
                                        <span class="date">{{item.pub_date}}</span>
                                        <p>{{item.content|slice:"0:100"}}...</p>
                                </div>
                            </li>
                        </a>
                    {% endfor %}
                    

                </ul>

                <nav aria-label="Page navigation example">
                    <ul class="pagination pg-blue">
                        {% for page in pages%}
                            {% if page == snews.number %}
                                <li class="page-item active">
                                    <span class="page-link">{{page}}</span>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a href="{% url 'polls:home'%}?page={{page}}&pub_date={{pub_date}}&title={{title}}" class="page-link"> {{page}} </a>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </nav>
                
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'polls/scripts/bootstrap-datepicker.min.js'%}"></script>
    <script>
        
        // russian datepicker
        !function (a) { a.fn.datepicker.dates.ru = { days: ["Воскресенье", "Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота"], daysShort: ["Вск", "Пнд", "Втр", "Срд", "Чтв", "Птн", "Суб"], daysMin: ["Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"], months: ["Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь"], monthsShort: ["Янв", "Фев", "Мар", "Апр", "Май", "Июн", "Июл", "Авг", "Сен", "Окт", "Ноя", "Дек"], today: "Сегодня", clear: "Очистить", format: "yyyy-mm-dd", weekStart: 1, monthsTitle: "Месяцы" } }(jQuery);
        // create datepicker
        $('#datepicker').datepicker({
            endDate: '0d',
            maxViewMode: 1,
            todayHighlight: true,
            autoclose: true,
            clearBtn: true,
            language: 'ru'
        });
        
        
    </script>
    <script>
    // Load the IFrame Player API code asynchronously.
    var tag = document.createElement('script');
    tag.src = "https://www.youtube.com/player_api";
    var firstScriptTag = document.getElementsByTagName('script')[0];
    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

    // Replace the 'ytplayer' element with an <iframe> and
    // YouTube player after the API code downloads.
    var player;
    function onYouTubePlayerAPIReady() {
        player = new YT.Player('ytplayer', {
        height: 'auto',
        width: '100%',
        videoId: '8T9SFZDP60Q'
        });
    }
    </script>
{% endblock %}



    

polls/templates/page.html
{% extends "base.html" %}
{% load static %}

{% block styles %}
        <link rel="stylesheet" href="{% static 'polls/styles/main.css'%}">
    <link rel="stylesheet" href="{% static 'polls/styles/bootstrap-datepicker.css'%}">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'polls/styles/new.css'%}">
{% endblock %}

{% block header_buttons %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'polls:home'%}">Главная</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">Популярное</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">О нас</a>
    </li>
{% endblock %}


{% block container %}
    <div class="container">
        <div class="row">
                <div class="col col-lg-12">
                        <img class="d-flex mr-3" src="{{current_new.img_url}}" alt="Generic placeholder image">
                        <div class="media-body">
                                <h5 class="mt-0 mb-1 font-weight-bold">{{current_new.title}}</h5>
                                <span>{{current_new.pub_date}}</span>
                                <p>{{current_new.content}}</p>
                        </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

polls/templates/popular.html
{% extends "base.html" %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'polls/styles/main.css'%}">
    <link rel="stylesheet" href="{% static 'polls/styles/bootstrap-datepicker.css'%}">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
{% endblock %}

{% block header_buttons %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'polls:home'%}">Главная</a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'polls:popular'%}">Популярное</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'polls:about'%}">О нас</a>
    </li>    
{% endblock %}

{% block input_block %}
    <input type="text" name="title" class="form-control search" placeholder="Введите название" value="{{title}}">
{% endblock %}

{% block container %}
    <div class="container">
        <div class="row">

            <!-- Video -->            
            <div class="col left">
                <h1 class="pg-title-tran">
                    Трансляция
                </h1>
                <div id="ytplayer" class="d-flex mr-3" ></div>    
                <img src="{% static 'polls/images/line.png'%}" alt="" class="line">                
            </div>

            <!-- News -->
            <div class="col col-lg-8">
                <h1 class="pg-title">
                    Популярное
                </h1>


                <!-- DATEPICKER -->
                <form action="" type="GET" class="input-group mb-3">
                    <input type="text" name="pub_date" autocomplete="off" value="{{pub_date}}" id="datepicker" class="form-control datepicker" placeholder="Выберите дату">
                    <div class="input-group-append">
                        <button class="btn" type="submit">Просмотреть новости</button>
                    </div>
                </form>
                <!-- <input type="hidden" id="my_hidden_input"> -->

                <ul class="list-unstyled">
                    {% for item in snews%}
                        <a href="{% url 'polls:new' item.url_name%}">
                            <li class="media my-4">
                                <img class="d-flex mr-3" src="{{item.img_url}}" alt="Generic placeholder image">                            
                                <div class="media-body">
                                        <h5 class="mt-0 mb-1 font-weight-bold">{{item.title}}</h5>
                                        <span class="date">{{item.pub_date}}</span>
                                        <p>{{item.content|slice:"0:100"}}...</p>
                                </div>
                            </li>
                        </a>
                    {% endfor %}
                    

                </ul>

                <nav aria-label="Page navigation example">
                    <ul class="pagination pg-blue">
                        {% for page in pages%}
                            {% if page == snews.number %}
                                <li class="page-item active">
                                    <span class="page-link">{{page}}</span>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a href="{% url 'polls:home'%}?page={{page}}&pub_date={{pub_date}}&title={{title}}" class="page-link"> {{page}} </a>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </nav>
                
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'polls/scripts/bootstrap-datepicker.min.js'%}"></script>
    <script>
        
        // russian datepicker
        !function (a) { a.fn.datepicker.dates.ru = { days: ["Воскресенье", "Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота"], daysShort: ["Вск", "Пнд", "Втр", "Срд", "Чтв", "Птн", "Суб"], daysMin: ["Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"], months: ["Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь"], monthsShort: ["Янв", "Фев", "Мар", "Апр", "Май", "Июн", "Июл", "Авг", "Сен", "Окт", "Ноя", "Дек"], today: "Сегодня", clear: "Очистить", format: "yyyy-mm-dd", weekStart: 1, monthsTitle: "Месяцы" } }(jQuery);
        // create datepicker
        $('#datepicker').datepicker({
            endDate: '0d',
            maxViewMode: 1,
            todayHighlight: true,
            autoclose: true,
            clearBtn: true,
            language: 'ru'
        });
        
        
    </script>
    <script>
    // Load the IFrame Player API code asynchronously.
    var tag = document.createElement('script');
    tag.src = "https://www.youtube.com/player_api";
    var firstScriptTag = document.getElementsByTagName('script')[0];
    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

    // Replace the 'ytplayer' element with an <iframe> and
    // YouTube player after the API code downloads.
    var player;
    function onYouTubePlayerAPIReady() {
        player = new YT.Player('ytplayer', {
        height: 'auto',
        width: '100%',
        videoId: '8T9SFZDP60Q'
        });
    }
    </script>
{% endblock %}



    